version: '3.4'

services:
  pythonprojects:
    image: pythonprojects
    build:
      context: .
      dockerfile: ./CoffeeBot/Dockerfile
      network_mode: host
    command: ["sh", "-c", "pip install debugpy -t /tmp && python /tmp/debugpy --wait-for-client --listen 0.0.0.0:5678 CoffeeBot/messaging.py "]
    ports:
      - 5678:5678
  